"""Compatibility shim. The implementation moved to `p4tools.coverage` in v0.19. This module re-exports the public API and emits a DeprecationWarning. Will be removed in v0.20."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/05g_production.coverage.ipynb.

# %% auto #0
__all__ = []

# %% ../../notebooks/05g_production.coverage.ipynb #7284770b
"""Compatibility shim — coverage moved to ``p4tools.coverage`` in v0.19."""
from warnings import warn

warn(
    "p4tools.production.coverage moved to p4tools.coverage in v0.19; "
    "the production.coverage import path will be removed in v0.20.",
    DeprecationWarning,
    stacklevel=2,
)

from p4tools.coverage import (  # noqa: F401,E402
    TILE_WIDTH_PX,
    TILE_HEIGHT_PX,
    TILE_AREA_PX,
    DEFAULT_CACHE_DIR,
    compute_per_tile_coverage,
    compute_per_obsid_coverage,
)

