# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/05c_production.metadata.ipynb.

# %% auto 0
__all__ = ['logger', 'MetadataReader', 'get_north_azimuths_from_SPICE']

# %% ../../notebooks/05c_production.metadata.ipynb 2
import logging
from planetarypy.pds.apps import get_index
from planetarypy.hirise import ProductPathfinder
import pandas as pd

from .projection import P4Mosaic

# %% ../../notebooks/05c_production.metadata.ipynb 3
logger = logging.getLogger(__name__)

# %% ../../notebooks/05c_production.metadata.ipynb 4
class MetadataReader:

    def __init__(self, obsid):
        self.obsid = obsid
        self.prodid = ProductPathfinder(obsid+"_COLOR")
        if not self.labelpath.exists():
            self.download_label()

    def read_edr_index(self):
        return get_index("mro.hirise", "edr")

    @property
    def labelpath(self):
        return self.prodid.local_label_path

    def download_label(self):
        self.prodid.download_label()

    @property
    def label(self):
        return labels.HiRISE_Label(self.labelpath)

    @property
    def campt_out_path(self):
        p4m = P4Mosaic(self.obsid)
        return p4m.mosaic_path.parent / f"{self.obsid}_campt_out.csv"

    @property
    def campt_out_df(self):
        return pd.read_csv(self.campt_out_path)


# %% ../../notebooks/05c_production.metadata.ipynb 5
def get_north_azimuths_from_SPICE(obsids):
    NAs = []
    for obsid in obsids:
        meta = MetadataReader(obsid)
        NAs.append(meta.campt_out_df['NorthAzimuth'].median())
    return pd.DataFrame(dict(OBSERVATION_ID=obsids, north_azimuth=NAs))
