"""Command-line interface for Planet Four catalog production."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/06_clis.ipynb.

# %% ../notebooks/06_clis.ipynb #cell-2
from __future__ import annotations

import logging
import sys
import tempfile
import base64
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor, as_completed
from typing import Optional

import typer
from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.progress import (
    Progress, SpinnerColumn, TextColumn,
    BarColumn, MofNCompleteColumn, TimeElapsedColumn,
)

import p4tools.production.io as io

# %% auto #0
__all__ = ['app', 'console', 'run_parallel_with_progress', 'setup', 'info', 'db_stats', 'random_tile', 'cluster_tile',
           'cluster_obsid', 'create_mosaic', 'produce']

# %% ../notebooks/06_clis.ipynb #cell-3
app = typer.Typer(
    name="p4",
    help="Planet Four catalog production tools.",
    rich_markup_mode="rich",
    no_args_is_help=True,
)
console = Console()

# %% ../notebooks/06_clis.ipynb #cell-4
def run_parallel_with_progress(
    func,
    items,
    max_workers: int = 4,
    description: str = "Processing",
    func_kwargs: dict | None = None,
):
    """Execute func(item, **func_kwargs) in parallel with a Rich progress bar.

    Parameters
    ----------
    func : callable
        A *picklable* top-level function.  Must accept a single positional
        argument (the item) plus any keyword arguments from *func_kwargs*.
    items : sequence
        Items to map over.
    max_workers : int
        Number of parallel processes.
    description : str
        Label shown in the progress bar.
    func_kwargs : dict, optional
        Extra keyword arguments forwarded to *func*.

    Returns
    -------
    results : list
        Successful results in the original item order (skipping failures).
    errors : list[tuple]
        ``(item, exception)`` pairs for items that raised.
    """
    if func_kwargs is None:
        func_kwargs = {}
    results, errors = {}, []
    items = list(items)
    with Progress(
        SpinnerColumn(),
        TextColumn("[bold blue]{task.description}"),
        BarColumn(),
        MofNCompleteColumn(),
        TimeElapsedColumn(),
    ) as progress:
        task = progress.add_task(description, total=len(items))
        with ProcessPoolExecutor(max_workers=max_workers) as executor:
            future_to_item = {
                executor.submit(func, item, **func_kwargs): item
                for item in items
            }
            for future in as_completed(future_to_item):
                item = future_to_item[future]
                try:
                    results[item] = future.result()
                except Exception as e:
                    errors.append((item, e))
                    progress.console.print(f"[red]Error {item}: {e}[/red]")
                progress.advance(task)
    return [results[item] for item in items if item in results], errors

# %% ../notebooks/06_clis.ipynb #cell-5
@app.command()
def setup(
    data_root: str = typer.Argument(help="Path where Planet Four results are stored."),
    db: Optional[str] = typer.Option(None, "--db", help="Path to raw P4 Parquet database."),
):
    """Configure the Planet Four data root (and optionally the raw database path)."""
    data_root_path = Path(data_root).expanduser().resolve()
    data_root_path.mkdir(parents=True, exist_ok=True)
    io.set_database_path(str(data_root_path))

    if db is not None:
        import configparser
        config = configparser.ConfigParser()
        config.read(str(io.configpath))
        if "planet4_db" not in config:
            config["planet4_db"] = {}
        config["planet4_db"]["dbname"] = str(Path(db).expanduser().resolve())
        with io.configpath.open("w") as f:
            config.write(f)

    console.print(Panel(
        f"[green]Data root:[/green] {data_root_path}\n"
        + (f"[green]Database:[/green]  {db}" if db else "[dim]No database path set.[/dim]"),
        title="Planet Four Configuration",
    ))

# %% ../notebooks/06_clis.ipynb #cell-6
@app.command()
def info():
    """Show current configuration and database summary."""
    table = Table(title="Planet Four Configuration")
    table.add_column("Key", style="cyan")
    table.add_column("Value", style="white")

    table.add_row("Config file", str(io.configpath))
    table.add_row("Config exists", str(io.configpath.exists()))

    if io.configpath.exists():
        config = io.get_config()
        for section in config.sections():
            for key, val in config[section].items():
                table.add_row(f"{section}.{key}", val)

        if io.data_root is not None:
            table.add_row("Data root", str(io.data_root))
            table.add_row("Data root exists", str(io.data_root.exists()))
    else:
        table.add_row("[yellow]Status[/yellow]", "[yellow]Not configured. Run 'p4 setup'.[/yellow]")

    console.print(table)

# %% ../notebooks/06_clis.ipynb #sccdt1lp2vg
@app.command()
def db_stats(
    db: Optional[str] = typer.Option(None, "--db", help="Path to raw P4 Parquet database. Reads from config if not given."),
    top: int = typer.Option(10, "--top", "-n", help="Number of top tiles/obsids to show."),
):
    """Show database statistics and top tiles/obsids by marking count."""
    try:
        stats = io.get_db_stats(db=db, top=top)
    except ValueError as e:
        console.print(f"[red]{e}[/red]")
        raise typer.Exit(1)

    console.print(f"Reading [cyan]{io.resolve_dbname(db)}[/cyan] ...")

    # --- Overview ---
    overview = Table(title="Database Overview")
    overview.add_column("Metric", style="cyan")
    overview.add_column("Value", justify="right")
    overview.add_row("Total markings", f"{stats['n_markings']:,}")
    overview.add_row("Unique tiles (image_id)", f"{stats['n_tiles']:,}")
    overview.add_row("Unique obsids (image_name)", f"{stats['n_obsids']:,}")
    overview.add_row("Avg markings / tile", f"{stats['avg_per_tile']:.1f}")
    overview.add_row("Avg markings / obsid", f"{stats['avg_per_obsid']:.1f}")

    for mtype, count in stats["type_counts"].items():
        overview.add_row(f"  {mtype}", f"{count:,}")

    console.print(overview)

    # --- Top tiles ---
    tile_table = Table(title=f"Top {top} Tiles by Marking Count")
    tile_table.add_column("#", style="dim", justify="right")
    tile_table.add_column("image_id (tile)", style="cyan")
    tile_table.add_column("image_name (obsid)", style="white")
    tile_table.add_column("Markings", justify="right", style="green")

    for rank, row in enumerate(stats["top_tiles"].itertuples(), 1):
        tile_table.add_row(str(rank), row.image_id, row.image_name, f"{row.markings:,}")

    console.print(tile_table)

    # --- Top obsids ---
    obsid_table = Table(title=f"Top {top} Obsids by Marking Count")
    obsid_table.add_column("#", style="dim", justify="right")
    obsid_table.add_column("image_name (obsid)", style="cyan")
    obsid_table.add_column("Tiles", justify="right")
    obsid_table.add_column("Markings", justify="right", style="green")

    for rank, row in enumerate(stats["top_obsids"].itertuples(), 1):
        obsid_table.add_row(str(rank), row.image_name, str(row.tiles), f"{row.markings:,}")

    console.print(obsid_table)

# %% ../notebooks/06_clis.ipynb #ynm78dvx91p
@app.command()
def random_tile(
    db: Optional[str] = typer.Option(None, "--db", help="Path to raw P4 Parquet database. Reads from config if not given."),
):
    """Print a random tile ID with a near-average marking count."""
    try:
        result = io.get_random_tile(db=db)
    except ValueError as e:
        console.print(f"[red]{e}[/red]")
        raise typer.Exit(1)

    console.print(
        f"[cyan]{result['image_id']}[/cyan]  "
        f"(obsid: {result['image_name']}, "
        f"markings: {result['markings']}, "
        f"avg: {result['avg']:.1f})"
    )

# %% ../notebooks/06_clis.ipynb #cell-7
def _display_inline_image(path: Path):
    """Display an image inline in the terminal using iTerm2 protocol.

    Falls back to printing the file path if the terminal does not support
    the iTerm2 inline image protocol.

    Parameters
    ----------
    path : Path
        Path to an image file (PNG/JPEG).
    """
    import os
    term_program = os.environ.get("TERM_PROGRAM", "")
    if term_program in ("iTerm.app", "WezTerm"):
        data = path.read_bytes()
        b64 = base64.b64encode(data).decode("ascii")
        sys.stdout.write(f"\033]1337;File=inline=1;size={len(data)}:{b64}\a")
        sys.stdout.write("\n")
        sys.stdout.flush()
    else:
        console.print(f"[dim]Plot saved to:[/dim] {path}")

# %% ../notebooks/06_clis.ipynb #cell-8
@app.command()
def cluster_tile(
    tile_id: str = typer.Argument(help="Planet Four tile image_id (e.g. APF00003qk)."),
    db: Optional[str] = typer.Option(None, "--db", help="Path to raw P4 Parquet database. Reads from config if not given."),
    savedir: Optional[str] = typer.Option(None, "--savedir", help="Directory for clustering output. Defaults to data_root/clustering."),
    plot: bool = typer.Option(True, help="Show an inline plot of the clustered markings."),
):
    """Cluster a single Planet Four tile and display the results."""
    from p4tools.production import markings, dbscan

    try:
        db = io.resolve_dbname(db)
    except ValueError as e:
        console.print(f"[red]{e}[/red]")
        raise typer.Exit(1)

    tile_id = io.check_and_pad_id(tile_id)
    console.print(f"Clustering tile [cyan]{tile_id}[/cyan] ...")

    # resolve obsid
    db_mgr = io.DBManager(dbname=db)
    obsid = db_mgr.get_obsid_for_tile_id(tile_id)
    console.print(f"  Obsid: [cyan]{obsid}[/cyan]")

    # cluster
    effective_savedir = savedir or "clustering"
    scanner = dbscan.DBScanner(savedir=effective_savedir, dbname=db)
    scanner.pm.obsid = obsid
    scanner.pm.id = tile_id
    scanner.cluster_image_id(tile_id, image_name=obsid)

    # read results
    pm = io.PathManager(id_=tile_id, obsid=obsid, datapath=effective_savedir)

    table = Table(title=f"Clustering Results for {tile_id}")
    table.add_column("Marking", style="cyan")
    table.add_column("Clusters", justify="right")
    table.add_column("File", style="dim")

    for kind, fpath in [("fans", pm.fanfile), ("blotches", pm.blotchfile)]:
        if fpath.exists():
            import pandas as pd
            df = pd.read_csv(fpath)
            table.add_row(kind, str(len(df)), str(fpath.name))
        else:
            table.add_row(kind, "0", "[dim]no file[/dim]")

    console.print(table)

    # inline plot
    if plot:
        try:
            import matplotlib
            matplotlib.use("Agg")
            import matplotlib.pyplot as plt

            p4id = markings.TileID(tile_id, dbname=db)
            fig, axes = plt.subplots(1, 3, figsize=(18, 6))

            # original markings
            p4id.show_subframe(ax=axes[0])
            axes[0].set_title("Tile image")

            # clustered fans
            p4id.show_subframe(ax=axes[1])
            if pm.fanfile.exists():
                import pandas as pd
                fan_df = pd.read_csv(pm.fanfile)
                p4id.plot_fans(data=fan_df, ax=axes[1], lw=1, with_center=True)
            axes[1].set_title(f"Fans ({len(fan_df) if pm.fanfile.exists() else 0})")

            # clustered blotches
            p4id.show_subframe(ax=axes[2])
            if pm.blotchfile.exists():
                import pandas as pd
                blotch_df = pd.read_csv(pm.blotchfile)
                p4id.plot_blotches(data=blotch_df, ax=axes[2], lw=1, with_center=True)
            axes[2].set_title(f"Blotches ({len(blotch_df) if pm.blotchfile.exists() else 0})")

            fig.suptitle(f"{tile_id} — {obsid}", fontsize=14)
            fig.tight_layout()

            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                fig.savefig(tmp.name, dpi=120, bbox_inches="tight")
                plt.close(fig)
                _display_inline_image(Path(tmp.name))
        except Exception as e:
            console.print(f"[yellow]Could not render plot: {e}[/yellow]")

# %% ../notebooks/06_clis.ipynb #cell-9
@app.command()
def cluster_obsid(
    obsid: str = typer.Argument(help="HiRISE observation ID (image_name)."),
    db: Optional[str] = typer.Option(None, "--db", help="Path to raw P4 Parquet database. Reads from config if not given."),
    savedir: Optional[str] = typer.Option(None, "--savedir", help="Output directory. Defaults to data_root/clustering."),
    fnotch: bool = typer.Option(False, "--fnotch/--no-fnotch", help="Also run fnotching after clustering."),
):
    """Cluster all tiles for a HiRISE observation ID."""
    from p4tools.production.catalog import cluster_obsid as _cluster_obsid, fnotch_obsid as _fnotch_obsid

    try:
        db = io.resolve_dbname(db)
    except ValueError as e:
        console.print(f"[red]{e}[/red]")
        raise typer.Exit(1)

    effective_savedir = savedir or "clustering"

    with console.status(f"Clustering [cyan]{obsid}[/cyan] ..."):
        _cluster_obsid(obsid=obsid, savedir=effective_savedir, dbname=db)

    console.print(f"[green]Clustering complete for {obsid}.[/green]")

    if fnotch:
        with console.status(f"Fnotching [cyan]{obsid}[/cyan] ..."):
            _fnotch_obsid(obsid=obsid, savedir=effective_savedir)
        console.print(f"[green]Fnotching complete for {obsid}.[/green]")

    # summary table
    pm = io.PathManager(obsid=obsid, datapath=effective_savedir)
    l1a_paths = pm.get_obsid_paths("L1A")

    table = Table(title=f"Results for {obsid}")
    table.add_column("Metric", style="cyan")
    table.add_column("Value", justify="right")
    table.add_row("Tiles processed", str(len(l1a_paths)))

    console.print(table)

# %% ../notebooks/06_clis.ipynb #5ee18ad8
@app.command()
def create_mosaic(
    obsid: str = typer.Argument(help="HiRISE observation ID (e.g. ESP_011350_0945)."),
    overwrite: bool = typer.Option(False, "--overwrite", help="Re-download and recreate even if mosaic exists."),
):
    """Create a RED45 mosaic cube for a single observation ID."""
    from p4tools.production.projection import create_RED45_mosaic

    console.print(f"Creating RED45 mosaic for [cyan]{obsid}[/cyan] ...")
    try:
        result = create_RED45_mosaic(obsid, overwrite=overwrite)
        console.print(f"[green]Mosaic created:[/green] {result}")
    except Exception as e:
        console.print(f"[red]Failed: {e}[/red]")
        raise typer.Exit(1)

# %% ../notebooks/06_clis.ipynb #cell-10
# Top-level picklable wrappers for ProcessPoolExecutor

def _cluster_single(obsid, savedir=None, dbname=None):
    """Picklable wrapper around catalog.cluster_obsid for parallel execution."""
    from p4tools.production.catalog import cluster_obsid as _cluster_obsid
    return _cluster_obsid(
        obsid=obsid, savedir=savedir, dbname=dbname,
    )


def _fnotch_single(obsid, savedir=None):
    """Picklable wrapper around catalog.fnotch_obsid for parallel execution."""
    from p4tools.production.catalog import fnotch_obsid as _fnotch_obsid
    return _fnotch_obsid(obsid=obsid, savedir=savedir)


def _create_mosaic_single(obsid):
    """Picklable wrapper around create_RED45_mosaic for parallel execution."""
    from p4tools.production.projection import create_RED45_mosaic
    return create_RED45_mosaic(obsid)

# %% ../notebooks/06_clis.ipynb #cell-11
@app.command()
def produce(
    version: str = typer.Argument(help="Catalog version string (e.g. v1.0)."),
    db: Optional[str] = typer.Option(None, "--db", help="Path to raw P4 Parquet database. Reads from config if not given."),
    workers: int = typer.Option(4, "--workers", "-w", help="Number of parallel workers."),
    dry_run: bool = typer.Option(False, "--dry-run", help="Show what would be done without executing."),
):
    """Run full catalog production with parallel processing and Rich progress."""
    from p4tools.production.catalog import (
        ReleaseManager, get_L1A_paths, add_marking_ids,
        fan_id_generator, blotch_id_generator, create_roi_file,
    )
    from p4tools.production.projection import create_RED45_mosaic

    try:
        db = io.resolve_dbname(db)
    except ValueError as e:
        console.print(f"[red]{e}[/red]")
        raise typer.Exit(1)

    rm = ReleaseManager(version=version, dbname=db)
    rm.check_for_todo()
    obsids = rm.todo

    console.print(Panel(
        f"[cyan]Version:[/cyan]  {version}\n"
        f"[cyan]Database:[/cyan] {db}\n"
        f"[cyan]Workers:[/cyan]  {workers}\n"
        f"[cyan]Obsids:[/cyan]   {len(obsids)} to process\n"
        f"[cyan]Save to:[/cyan]  {rm.savefolder}",
        title="Catalog Production Plan",
    ))

    if dry_run:
        console.print("[yellow]Dry run — no work performed.[/yellow]")
        if len(obsids) <= 20:
            for obs in obsids:
                console.print(f"  {obs}")
        return

    # Use rm.catalog (e.g. "P4_catalog_v3.1") as savedir for all phases,
    # matching the convention used by ReleaseManager's own methods.
    savedir = rm.catalog

    # --- Phase 1: Clustering (parallel) ---
    if len(obsids) == 0:
        console.print("[green]Phase 1: All obsids already clustered — skipping.[/green]")
    else:
        console.rule("[bold]Phase 1: Clustering[/bold]")
        _, cluster_errors = run_parallel_with_progress(
            _cluster_single, obsids, max_workers=workers,
            description="Clustering obsids",
            func_kwargs={"savedir": savedir, "dbname": db},
        )
        if cluster_errors:
            console.print(f"[red]{len(cluster_errors)} obsids failed clustering.[/red]")

    # --- Phase 1b: Add marking IDs to L1A results ---
    # get_L1A_paths returns directories; check CSV files inside for marking_id
    all_l1a = []
    for obs in rm.obsids:
        all_l1a.extend(get_L1A_paths(obs, savedir))
    needs_ids = []
    for p in all_l1a:
        image_id = p.parent.name
        fan_csv = p / f"{image_id}_L1A_fans.csv"
        blotch_csv = p / f"{image_id}_L1A_blotches.csv"
        has_id = True
        for csv in [fan_csv, blotch_csv]:
            if csv.exists():
                with open(csv) as f:
                    header = f.readline()
                if "marking_id" not in header:
                    has_id = False
                    break
        if not has_id:
            needs_ids.append(p)
    if needs_ids:
        console.print(f"  Adding marking IDs to {len(needs_ids)} L1A directories ...")
        fan_id = fan_id_generator()
        blotch_id = blotch_id_generator()
        for p in needs_ids:
            add_marking_ids(p, fan_id, blotch_id)
        console.print("  [green]Marking IDs added.[/green]")
    else:
        console.print("[green]All L1A files already have marking IDs.[/green]")

    # --- Phase 2: Fnotching (parallel) ---
    # Always run all obsids — per-tile .done sentinels handle skipping
    # inside fnotch_image_ids / apply_cut.
    console.rule("[bold]Phase 2: Fnotching[/bold]")
    console.print(f"  {len(rm.obsids)} obsids to fnotch")
    _, fnotch_errors = run_parallel_with_progress(
        _fnotch_single, rm.obsids, max_workers=workers,
        description="Fnotching obsids",
        func_kwargs={"savedir": savedir},
    )
    if fnotch_errors:
        console.print(f"[red]{len(fnotch_errors)} obsids failed fnotching.[/red]")

    # --- Production report: collect failures across all phases ---
    import json as _json
    from datetime import datetime
    report = {
        "version": version,
        "started": datetime.now().isoformat(),
        "total_obsids": len(rm.obsids),
        "failures": {},
    }

    # --- Phase 2.5: Create RED45 mosaics for ground projection ---
    console.rule("[bold]Creating RED45 Mosaics[/bold]")
    _, mosaic_errors = run_parallel_with_progress(
        _create_mosaic_single, rm.obsids, max_workers=workers,
        description="Creating RED45 mosaics",
    )
    if mosaic_errors:
        console.print(f"[red]{len(mosaic_errors)} obsids failed mosaic creation.[/red]")
        report["failures"]["mosaic_creation"] = [
            {"obsid": obs, "reason": str(err)} for obs, err in mosaic_errors
        ]

    # --- Phase 3: Post-processing (serial) ---
    console.rule("[bold]Phase 3: Post-processing[/bold]")

    with console.status("Creating L1C summary files ..."):
        create_roi_file(rm.obsids, rm.catalog, savedir)
    console.print("  [green]L1C summary files created.[/green]")

    console.print("  Calculating tile coordinates ...")
    failed_campt, skipped_tiles = rm.calc_tile_coordinates()
    console.print(f"  [green]Tile coordinates calculated.[/green]")
    if failed_campt:
        console.print(f"  [red]{len(failed_campt)} obsids failed campt.[/red]")
        report["failures"]["tile_coords_campt"] = [
            {"cubepath": p, "reason": "campt failed (missing SPICE data)"} for p in failed_campt
        ]
    if skipped_tiles:
        report["failures"]["tile_coords_missing"] = [
            {"cubepath": p, "reason": "no tile coord output file"} for p in skipped_tiles
        ]

    console.print("  Calculating marking coordinates ...")
    failed_markings = rm.calc_marking_coordinates()
    console.print(f"  [green]Marking coordinates calculated.[/green]")
    if failed_markings:
        console.print(f"  [red]{len(failed_markings)} obsids failed marking coord projection.[/red]")
        report["failures"]["marking_coords"] = [
            {"obsid": obs, "reason": "campt/spiceinit failed for mosaic"} for obs in failed_markings
        ]

    console.print("  Writing metadata ...")
    skipped_metadata = rm.calc_metadata()
    console.print("  [green]Metadata written.[/green]")
    if skipped_metadata:
        console.print(f"  [red]{len(skipped_metadata)} obsids missing north azimuth (no campt output).[/red]")
        report["failures"]["metadata_north_azimuth"] = [
            {"obsid": obs, "reason": "no campt_out.csv — cannot compute north azimuth"} for obs in skipped_metadata
        ]

    with console.status("Merging all catalog data ..."):
        rm.merge_all()
    console.print("  [green]Catalog merged.[/green]")

    # --- Phase 4: Marking IDs (serial, final step) ---
    console.rule("[bold]Phase 4: Assigning Marking IDs[/bold]")
    with console.status("Assigning unique marking IDs ..."):
        rm.fix_marking_ids()
    console.print("  [green]Marking IDs assigned.[/green]")

    # --- Write production report ---
    report["finished"] = datetime.now().isoformat()
    report_path = rm.savefolder / f"{rm.catalog}_production_report.json"
    with open(report_path, "w") as f:
        _json.dump(report, f, indent=2)

    # Print summary
    total_failures = sum(len(v) for v in report["failures"].values())
    if total_failures > 0:
        console.rule("[bold red]Production Report: Failures[/bold red]")
        failed_obsids = set()
        for phase, items in report["failures"].items():
            for item in items:
                obsid = item.get("obsid") or Path(item.get("cubepath", "")).stem.split("_mosaic")[0]
                failed_obsids.add(obsid)
                console.print(f"  [red]{phase}[/red]: {obsid} — {item['reason']}")
        console.print(f"\n  [bold red]{len(failed_obsids)} unique obsid(s) with issues out of {len(rm.obsids)} total.[/bold red]")
        console.print(f"  Full report: {report_path}")
    else:
        console.print(f"\n  [green]No failures — all {len(rm.obsids)} obsids processed successfully.[/green]")

    console.print(Panel(
        f"[green]Catalog production complete![/green]\n"
        f"Output: {rm.savefolder}\n"
        f"Report: {report_path}",
        title="Done",
    ))
