"""This module takes care of receiving the data catalogs."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/00_io.ipynb.

# %% auto #0
__all__ = ['logger', 'v1', 'kwargs', 'v3', 'v3_1', 'fetchers', 'mars_years', 'postprocessor', 'set_catalog_version',
           'catalog_version', 'get_metafull', 'get_blotch_catalog', 'get_fan_catalog', 'get_tile_coords',
           'get_meta_data', 'get_region_names', 'get_tile_urls', 'define_martian_year', 'normalize_tile_id',
           'get_subframe', 'get_url_for_tile_id', 'get_url_for_tile', 'is_tile_cached', 'get_subframe_by_tile_id',
           'get_subframe_for_tile', 'get_cached_tile_ids', 'get_fans_for_tile', 'get_blotches_for_tile', 'get_hirise_id_for_tile', 'attach_my',
           'attach_roi']

# %% ../notebooks/00_io.ipynb #53d83d54
from contextlib import contextmanager
from functools import cache
from pathlib import Path
import warnings

import matplotlib.image as mplimg
import pandas as pd
import pooch
from matplotlib import pyplot as plt

# %% ../notebooks/00_io.ipynb #a74ae6f5
logger = pooch.get_logger()
logger.setLevel("DEBUG")

# %% ../notebooks/00_io.ipynb #2b888530
v1 = pooch.create(
    path=pooch.os_cache("p4tools"),
    base_url="",
    version="v1",
    registry={
        "fans": "md5:71ff51ff79d6e975f704f19b1996d8ea",
        "blotches": "md5:f4d0c101f65abbaf34e092620133d56e",
        "metadata": "md5:c0dc46e0fc3d259c30afaec412074eae",
        "tile_coords": "md5:6b9a917a6997f1aa01cfef4322cabd81",
        "raw_data": "md5:39a8909590fe9f816454db93f0027d2c",
        "intermediate": "md5:6544bf0c7851eedd4783859c0adc42d7",
        "region_names": "md5:9101c7a0f8e248c9ffe9c07869da5635",
        "tile_urls": "md5:5717c8379d453cf4b11a5f5775f5fb6e",
    },
    urls={
        "fans": "doi:10.5281/zenodo.8102805/P4_catalog_v1.1_L1C_cut_0.5_fan.csv.zip",
        "blotches": "doi:10.5281/zenodo.8102805/P4_catalog_v1.1_L1C_cut_0.5_blotch.csv.zip",
        "metadata": "doi:10.5281/zenodo.8102805/P4_catalog_v1.1_metadata.csv.zip",
        "tile_coords": "doi:10.5281/zenodo.8102805/P4_catalog_v1.1_tile_coords_final.csv.zip",
        "raw_data": "doi:10.5281/zenodo.8102805/P4_catalog_v1.0_raw_classifications.hdf.zip",
        "intermediate": "doi:10.5281/zenodo.8102805/P4_catalog_v1.0_pipeline_products.zip",
        "region_names": "doi:10.5281/zenodo.8102805/region_names.zip",
        "tile_urls": "doi:10.5281/zenodo.8102805/tile_urls.csv.zip",
    },
)

# %% ../notebooks/00_io.ipynb #dc38c6ce
def postprocessor(fname, action, pup):
    """
    Post-processing hook to process the downloaded v1 catalog file.

    Postprocessing steps are:
    1. unzip to CSV
    2. load CSV into pandas
    3. save as parquet file.

    This time, at the next read, the performance is much increased due to reading the parquet file instead of loading
    the CSV file every time.

    Parameters
    ----------
    fname : str
       Full path of the zipped file in local storage
    action : str
       One of "download" (file doesn't exist and will download),
       "update" (file is outdated and will download), and
       "fetch" (file exists and is updated so no download).
    pup : Pooch
       The instance of Pooch that called the processor function.

    Returns
    -------
    fname : str
       The full path to the unzipped file. (Return the same fname is your
       processor doesn't modify the file).

    """
    fpath = Path(fname)
    if pup.urls[fpath.name].endswith(".zip"):
        unzipper = pooch.Unzip()
        csvfname = unzipper(fname, action, pup)[0]
    else:
        csvfname = fname
    parquetfname = Path(csvfname).with_suffix(".parq")
    if action in ("update", "download") or not parquetfname.is_file():
        logger.info(f"Converting CSV to parquet and storing as {parquetfname}.")
        pd.read_csv(csvfname).to_parquet(parquetfname)
    return parquetfname

# %% ../notebooks/00_io.ipynb #cae701fe
kwargs = dict(processor=postprocessor, progressbar=True)

# %% ../notebooks/00_io.ipynb #502b7647
v3 = pooch.create(
    path=pooch.os_cache("p4tools"),
    base_url="",
    version="v3",
    registry={
        "fans": "md5:186c98dee8712dcab1ea08317e60ed9b",
        "blotches": "md5:651d767533f70196ab36512eff01a941",
        "metafull": "md5:5c2e5f34e2b9c98b18b35ed5e16f68b4",
        "tile_coords": "md5:adb3958c7ff2f80385ddcf4c6a7b8da1",
        "metadata": "md5:fa1ed90fd731fabc0f760b2d51759b4f",
    },
    urls={
        "fans": "https://refubium.fu-berlin.de/bitstream/handle/fub188/46287/P4_catalog_Full_Release_v3.0_L1C_cut_0.5_fan_meta_merged.csv",
        "blotches": "https://refubium.fu-berlin.de/bitstream/handle/fub188/46287/P4_catalog_Full_Release_v3.0_L1C_cut_0.5_blotch_meta_merged.csv",
        "metafull": "https://refubium.fu-berlin.de/bitstream/handle/fub188/46287/P4_catalog_Full_Release_v3.0_EDRINDEX_metadata.csv",
        "tile_coords": "https://refubium.fu-berlin.de/bitstream/handle/fub188/46287/P4_catalog_Full_Release_v3.0_tile_coords_final.csv",
        "metadata": "https://refubium.fu-berlin.de/bitstream/handle/fub188/46287/P4_catalog_Full_Release_v3.0_metadata.csv",
    },
)

# %% ../notebooks/00_io.ipynb #o4yi4xuj31
v3_1 = pooch.create(
    path=pooch.os_cache("p4tools"),
    base_url="",
    version="v3.1",
    registry={
        "fans":       "md5:2fc5ad525ad3ae4c583fe4baad6dbb44",
        "blotches":   "md5:44ef0e3d27c8ac8c53d7a63aed211d26",
        "metafull":   "md5:de1f26c12bf3de2600b4f64eb96d15a6",
        "tile_coords":"md5:2e206ba6bebf8d293c28bfc52886080c",
        "metadata":   "md5:0245c87ebfa6afc30e4dc826c3c468b0",
        "region_names": "md5:9090f80faeb215819215362d2800bec6",
    },
    urls={
        "fans":       "doi:10.5281/zenodo.19057090/P4_catalog_v3.1_L1C_cut_0.5_fan_meta_merged.csv",
        "blotches":   "doi:10.5281/zenodo.19057090/P4_catalog_v3.1_L1C_cut_0.5_blotch_meta_merged.csv",
        "metafull":   "doi:10.5281/zenodo.19057090/P4_catalog_v3.1_EDRINDEX_metadata.csv",
        "tile_coords":"doi:10.5281/zenodo.19057090/P4_catalog_v3.1_tile_coords_final.csv",
        "metadata":   "doi:10.5281/zenodo.19057090/P4_catalog_v3.1_metadata.csv",
        "region_names": "doi:10.5281/zenodo.20054858/P4_catalog_v3.1_region_names.csv",
    },
)

# %% ../notebooks/00_io.ipynb #9957394b
fetchers = {"v1": v1.fetch, "v3": v3.fetch, "v3.1": v3_1.fetch}

# %% ../notebooks/00_io.ipynb #udrfblsf22e
_DEFAULT_VERSION = "v3.1"


def set_catalog_version(version: str):
    """Set the default catalog version for the current session/notebook.

    Parameters
    ----------
    version : str
        Catalog version string, e.g. ``'v3.1'``, ``'v3'``, ``'v1'``.

    Examples
    --------
    >>> set_catalog_version('v3.1')
    """
    global _DEFAULT_VERSION
    _DEFAULT_VERSION = version


@contextmanager
def catalog_version(version: str):
    """Context manager to temporarily use a different catalog version.

    Parameters
    ----------
    version : str
        Catalog version string, e.g. ``'v3.1'``, ``'v3'``, ``'v1'``.

    Examples
    --------
    >>> with catalog_version('v3'):
    ...     fans = get_fan_catalog()
    """
    global _DEFAULT_VERSION
    old = _DEFAULT_VERSION
    _DEFAULT_VERSION = version
    try:
        yield
    finally:
        _DEFAULT_VERSION = old


def _resolve_version(version):
    "Return version if explicitly given, otherwise fall back to _DEFAULT_VERSION. Normalises e.g. 'v1.0' → 'v1'."
    v = version if version is not None else _DEFAULT_VERSION
    if v not in fetchers and v.endswith(".0"):
        v = v[:-2]  # strip trailing .0: v1.0 → v1, v3.0 → v3
    return v

# %% ../notebooks/00_io.ipynb #38bb864f
def get_metafull(version=None) -> pd.DataFrame:
    "only v3 and v3.1 exist"
    version = _resolve_version(version)
    fetch = fetchers[version] if version in ("v3", "v3.1") else fetchers["v3"]
    df = pd.read_parquet(fetch("metafull", **kwargs)).drop("Unnamed: 0", axis=1, errors="ignore")
    return define_martian_year(df, "OBSERVATION_START_TIME")


def get_blotch_catalog(version=None) -> pd.DataFrame:
    version = _resolve_version(version)
    bl = pd.read_parquet(fetchers[version]("blotches", **kwargs))
    meta = get_metafull(version)
    return bl.set_index("obsid").join(meta.set_index("OBSERVATION_ID")["MY"]).reset_index()


def get_fan_catalog(version=None) -> pd.DataFrame:
    version = _resolve_version(version)
    fans = pd.read_parquet(fetchers[version]("fans", **kwargs))
    meta = get_metafull(version)
    return fans.set_index("obsid").join(meta.set_index("OBSERVATION_ID")["MY"]).reset_index()


def get_tile_coords(version=None) -> pd.DataFrame:
    version = _resolve_version(version)
    return pd.read_parquet(fetchers[version]("tile_coords", **kwargs))


def get_meta_data(version=None) -> pd.DataFrame:
    version = _resolve_version(version)
    return pd.read_parquet(fetchers[version]("metadata", **kwargs))


def get_region_names(version=None) -> pd.DataFrame:
    """Per-obsid ROI assignments.

    v3.1 (default) includes the 11 MY-33 obsids that are missing from the
    v1 mapping (5 Manhattan_Classic + 6 Ithaca). v1 is kept available for
    historical reproduction.
    """
    version = _resolve_version(version) if version is not None else "v3.1"
    if version in ("v3", "v3.1"):
        return pd.read_parquet(fetchers["v3.1"]("region_names", **kwargs))
    if version == "v1":
        return pd.read_parquet(v1.fetch("region_names", **kwargs))
    raise ValueError(f"region_names not available for version {version!r}")


def get_tile_urls() -> pd.DataFrame:
    "only v1 exists"
    return pd.read_parquet(v1.fetch("tile_urls", **kwargs))


mars_years = {
    28: "2006-01-23",
    29: "2007-12-10",
    30: "2009-10-27",
    31: "2011-09-15",
    32: "2013-08-01",
    33: "2015-06-19",
    34: "2017-05-05",
    35: "2019-03-24",
    36: "2021-02-07",
    37: "2022-12-26",
    38: "2024-11-24",
    39: "2026-09-30",
    40: "2028-08-17",
}


def define_martian_year(df, time_col_name):
    """Add Martian Year (MY) column to dataframe based on time column.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame to modify
    time_col_name : str
        Name of the time column to use for MY calculation

    Returns
    -------
    pd.DataFrame
        DataFrame with added 'MY' column
    """
    mars_timestamps = {k: pd.to_datetime(v) for k, v in mars_years.items()}

    # Convert time column to datetime if it's not already
    if not pd.api.types.is_datetime64_any_dtype(df[time_col_name]):
        df[time_col_name] = pd.to_datetime(df[time_col_name])

    df["MY"] = 0
    for yr, t in mars_timestamps.items():
        df.loc[df[time_col_name] > t, "MY"] = yr

    return df

# %% ../notebooks/00_io.ipynb #8ed80c5d
def normalize_tile_id(tile_id: str) -> str:
    """Normalize a tile ID by adding 'APF' prefix and leading zeros if necessary.

    Parameters
    ----------
    tile_id : str
        Full or partial tile ID. If partial, it will be padded with 'APF' and leading zeros.

    Returns
    -------
    str
        Complete tile ID in format 'APF0000xxx' (always 9 characters)

    Examples
    --------
    >>> normalize_tile_id('r8y')
    'APF0000r8y'
    >>> normalize_tile_id('0000r8y')
    'APF0000r8y'
    >>> normalize_tile_id('APF0000r8y')
    'APF0000r8y'
    >>> normalize_tile_id('123r8y')
    'APF0123r8y'
    """
    # Remove 'APF' prefix if present
    if tile_id.upper().startswith("APF"):
        tile_id = tile_id[3:]

    # Calculate how many zeros we need to add
    target_length = 7  # length without 'APF'
    current_length = len(tile_id)

    if current_length > target_length:
        raise ValueError(f"Tile ID too long: {tile_id}")

    # Add necessary leading zeros
    padded_id = "0" * (target_length - current_length) + tile_id

    # Add APF prefix
    return f"APF{padded_id}"

# %% ../notebooks/00_io.ipynb #51bf8f13
@cache
def _tile_url_series():
    """Cached ``tile_id -> tile_url`` mapping, built once per process.

    Call ``_tile_url_series.cache_clear()`` to refresh after the tile_urls
    table changes.
    """
    return get_tile_urls().set_index("tile_id")["tile_url"]


def _cache_path_for_url(url):
    "Path where pooch stores (or would store) the subframe image for `url`."
    from pooch import utils

    return Path(pooch.os_cache("p4tools/tiles")) / utils.unique_file_name(url)


def get_subframe(url, download=True):
    """Load a subframe image for `url` from the local pooch cache.

    Parameters
    ----------
    url : str
        Full subframe image URL.
    download : bool, default True
        If False and the image is not already cached, raise instead of
        attempting a network download (the origin host is offline).
    """
    path = _cache_path_for_url(url)
    if not download and not path.exists():
        raise FileNotFoundError(f"Subframe not cached and download disabled: {url}")
    targetpath = pooch.retrieve(
        url, path=path.parent, known_hash=None, progressbar=True
    )
    return mplimg.imread(targetpath)

# %% ../notebooks/00_io.ipynb #6c73fc78
def get_url_for_tile_id(tile_id):
    "Return the subframe image URL for `tile_id`."
    tid = normalize_tile_id(tile_id)
    try:
        return _tile_url_series().at[tid]
    except KeyError:
        raise KeyError(
            f"No subframe URL for tile_id {tid!r} in the tile_urls table."
        ) from None


def get_url_for_tile(tile_id):
    "Deprecated alias for `get_url_for_tile_id`."
    warnings.warn(
        "get_url_for_tile is deprecated; use get_url_for_tile_id.",
        DeprecationWarning,
        stacklevel=2,
    )
    return get_url_for_tile_id(tile_id)


def is_tile_cached(tile_id):
    "True if the subframe image for `tile_id` is already in the local cache."
    return _cache_path_for_url(get_url_for_tile_id(tile_id)).exists()

# %% ../notebooks/00_io.ipynb #fe2ef8be
def get_subframe_by_tile_id(tile_id, download=True):
    "Load the subframe image for `tile_id` from the local cache."
    url = get_url_for_tile_id(tile_id)
    return get_subframe(url, download=download)


def get_subframe_for_tile(tile_id):
    "Deprecated alias for `get_subframe_by_tile_id`."
    warnings.warn(
        "get_subframe_for_tile is deprecated; use get_subframe_by_tile_id.",
        DeprecationWarning,
        stacklevel=2,
    )
    return get_subframe_by_tile_id(tile_id)

# %% ../notebooks/00_io.ipynb #c9f4d1e7
def get_cached_tile_ids():
    """Reverse-map the local subframe cache to the tile_ids available offline.

    Scans the pooch tiles cache (``pooch.os_cache("p4tools/tiles")``), where each
    file is named ``<md5(url)>-<subject>.jpg``, and maps it back to its tile_id via
    `get_tile_urls`. Only files whose name matches ``pooch.utils.unique_file_name``
    of the looked-up URL are counted, so stray files are ignored.

    Returns
    -------
    list of str
        Sorted tile_ids whose subframe image is present in the local cache.
    """
    cache_dir = Path(pooch.os_cache("p4tools/tiles"))
    if not cache_dir.exists():
        return []
    urls = _tile_url_series()
    # subject-basename -> tile_id; basenames are unique in the table
    base2tid = {u.rsplit("/", 1)[-1]: tid for tid, u in urls.items()}
    found = []
    for f in cache_dir.iterdir():
        if not f.is_file() or "-" not in f.name:
            continue
        tid = base2tid.get(f.name.split("-", 1)[1])
        if tid is not None and f == _cache_path_for_url(urls.at[tid]):
            found.append(tid)
    return sorted(found)

# %% ../notebooks/00_io.ipynb #c8dfc110
def get_fans_for_tile(tile_id, version=None):
    version = _resolve_version(version)
    tile_id = normalize_tile_id(tile_id)
    fans = get_fan_catalog(version)
    result = fans.query("tile_id == @tile_id")
    if result.empty:
        tc = get_tile_coords(version)
        if tile_id not in tc["tile_id"].values:
            warnings.warn(
                f"Tile {tile_id} is not in the {version} catalog — its observation "
                f"was not included in this release. Try a different version.",
                UserWarning, stacklevel=2,
            )
    return result

# %% ../notebooks/00_io.ipynb #041e25b4
def get_blotches_for_tile(tile_id, version=None):
    version = _resolve_version(version)
    tile_id = normalize_tile_id(tile_id)
    blotches = get_blotch_catalog(version)
    result = blotches.query("tile_id == @tile_id")
    if result.empty:
        tc = get_tile_coords(version)
        if tile_id not in tc["tile_id"].values:
            warnings.warn(
                f"Tile {tile_id} is not in the {version} catalog — its observation "
                f"was not included in this release. Try a different version.",
                UserWarning, stacklevel=2,
            )
    return result

# %% ../notebooks/00_io.ipynb #89e455cd
def get_hirise_id_for_tile(tile_id, version=None):
    version = _resolve_version(version)
    tile_id = normalize_tile_id(tile_id)
    try:
        obsid = get_fans_for_tile(tile_id, version).obsid.iloc[0]
    except IndexError:
        try:
            obsid = (
                get_blotch_catalog(version).query("tile_id == @tile_id").obsid.iloc[0]
            )
        except IndexError:
            raise ValueError(f"No obsid found for tile {tile_id}")
    else:
        return obsid

# %% ../notebooks/00_io.ipynb #a1892936
def attach_my(df, *, obsid_col: str = "obsid", version: str = "v3.1"):
    """Left-join ``df`` with metafull[OBSERVATION_ID, MY, SOLAR_LONGITUDE].

    The metafull columns are renamed to ``obsid``, ``MY``, ``l_s``.
    """
    meta = (
        get_metafull(version)[["OBSERVATION_ID", "MY", "SOLAR_LONGITUDE"]]
        .rename(columns={"OBSERVATION_ID": obsid_col, "SOLAR_LONGITUDE": "l_s"})
    )
    return df.merge(meta, on=obsid_col, how="left")


def attach_roi(df, *, obsid_col: str = "obsid", version: str = "v3.1"):
    """Left-join ``df`` with `get_region_names(version=...)[obsid, roi_name]`."""
    rn = get_region_names(version=version)[["obsid", "roi_name"]]
    if obsid_col != "obsid":
        rn = rn.rename(columns={"obsid": obsid_col})
    return df.merge(rn, on=obsid_col, how="left")
