"""Module to work with both fan and blotch markings graphically."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/01_markings.ipynb.

# %% auto #0
__all__ = ['IMG_X_SIZE', 'IMG_Y_SIZE', 'calc_fig_size', 'show_subframe', 'set_subframe_size', 'MarkingMixin', 'Blotch',
           'MarkingCollection', 'Blotches', 'rotate_vector', 'Fan', 'Fans', 'markings_to_geoseries']

# %% ../notebooks/01_markings.ipynb #ecd67213
import math
from math import cos, degrees, pi, radians, sin
from pathlib import Path

import matplotlib.lines as lines
import matplotlib.patches as mpatches
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from matplotlib.collections import PatchCollection, LineCollection
from matplotlib.patches import Ellipse
from numpy import arctan2
from numpy import linalg as LA
from shapely import affinity
from shapely import geometry as geom

from . import io

# %% ../notebooks/01_markings.ipynb #1aa82587
IMG_X_SIZE = 840
IMG_Y_SIZE = 648

# %% ../notebooks/01_markings.ipynb #0f4cea08
def calc_fig_size(width):
    """Calc figure height in ratio of subframes."""
    ratio = IMG_X_SIZE / IMG_Y_SIZE
    return (width, width / ratio)

# %% ../notebooks/01_markings.ipynb #f89a869c
def show_subframe(tile_id, ax=None, aspect="auto"):
    subframe = io.get_subframe_by_tile_id(tile_id)
    if ax is None:
        _, ax = plt.subplots(figsize=calc_fig_size(8))
    ax.imshow(subframe, origin="upper", aspect=aspect)
    ax.set_axis_off()
    return ax

# %% ../notebooks/01_markings.ipynb #64beffa1
def set_subframe_size(ax):
    """Set plot view limit on Planet 4 subframe size."""
    ax.set_xlim(0, IMG_X_SIZE)
    ax.set_ylim(IMG_Y_SIZE, 0)

# %% ../notebooks/01_markings.ipynb #s3bjtiz98yh
def _remove_artist(obj, attr_name):
    """Remove a matplotlib artist stored as ``obj.<attr_name>`` if present.

    Silently ignores removal errors so repeated plotting is idempotent.
    """
    artist = getattr(obj, attr_name, None)
    if artist is not None:
        try:
            artist.remove()
        except Exception:
            pass
        setattr(obj, attr_name, None)


class MarkingMixin:
    """Shared behavior for Blotch and Fan single-marking classes.

    Subclasses must define:
    - ``to_average``: list of field names
    - ``_catalog_getter``: staticmethod returning catalog DataFrame
    - ``data``: backing pandas Series
    """

    @classmethod
    def from_tile_id(cls, tile_id, n=0, **kwargs):
        df = cls._catalog_getter()
        data = df[df.tile_id == tile_id].iloc[n]
        return cls(data, **kwargs)

    @classmethod
    def from_marking_id(cls, marking_id, version=None, **kwargs):
        """Factory to create a marking from a stable marking_id."""
        if version is None:
            df = cls._catalog_getter()
        else:
            try:
                df = cls._catalog_getter(version)
            except TypeError:
                df = cls._catalog_getter()
        sel = df[df.marking_id == marking_id]
        if sel.empty:
            raise KeyError(f"marking_id {marking_id!r} not found in {cls.__name__.lower()} catalog")
        return cls(sel.squeeze(), **kwargs)

    @property
    def tile_id(self):
        try:
            return self.data.tile_id
        except AttributeError:
            return self.data.image_id

    @property
    def n_members(self):
        return self._n_members

    @n_members.setter
    def n_members(self, value):
        self._n_members = value

    def is_equal(self, other):
        return all(
            getattr(self.data, f) == getattr(other.data, f)
            for f in self.to_average
        )

    def to_shapely_ground(self, crs=None, body="mars", system="ocentric"):
        """Exact ``to_shapely()`` outline projected to ground coordinates.

        Returns the marking outline as a shapely polygon in ``crs`` (any
        pyproj/rasterio/cartopy CRS) or, if ``crs`` is None, in body geographic
        lon/lat. Requires the catalog projection columns ``Longitude``,
        ``PlanetocentricLatitude``, ``north_azimuth`` and ``map_scale``.
        """
        d = self.data
        try:
            lon0, lat0 = d.Longitude, d.PlanetocentricLatitude
            na, ms = d.north_azimuth, d.map_scale
        except AttributeError as e:
            raise KeyError(
                "marking data lacks projection columns (Longitude, "
                "PlanetocentricLatitude, north_azimuth, map_scale); build the "
                "marking from a published catalog row"
            ) from e
        sx, sy = ("x", "y") if self.scope == "planet4" else ("image_x", "image_y")
        poly = np.asarray(self.to_shapely().exterior.coords)
        lon, lat = _pixel_offsets_to_lonlat(
            poly[:, 0] - getattr(d, sx), poly[:, 1] - getattr(d, sy),
            lon0, lat0, na, ms, _body_crs(body, system).get_geod())
        return geom.Polygon(_to_target(np.column_stack([lon, lat]), crs, body, system))


# %% ../notebooks/01_markings.ipynb #83e236ef
class Blotch(MarkingMixin, Ellipse):
    _catalog_getter = staticmethod(io.get_blotch_catalog)
    to_average = "x y image_x image_y angle radius_1 radius_2".split()

    def __init__(
        self,
        data,  # object with blotch data attributes: x, y, radius_1, radius_2, angle
        scope="planet4",  # "planet4" or "hirise",
        with_center=False,  # if True, plot the center of the blotch,
        url_db="",  # path to the url database,
        **kwargs,
    ):
        """
        Blotch management class for P4.

        Attributes
        ----------
        to_average : list
            List of cols to be averaged after clustering
        data : object with blotch data attributes, as provided by `data`
        center : tuple (inherited from matplotlib.Ellipse)
            Coordinates of center, i.e. self.x, self.y
        """
        self.data = data
        self.scope = scope if scope is not None else "planet4"
        self.with_center = with_center
        self.url_db = Path(url_db)
        self.ax = None
        if scope not in ["hirise", "planet4"]:
            raise TypeError("Unknown scope: {}".format(scope))
        try:
            self.x = data.x if scope == "planet4" else data.image_x
            self.y = data.y if scope == "planet4" else data.image_y
        except AttributeError:
            print("No x and y attributes in data:\n{}".format(data))
            raise AttributeError
        # default member number is 1. This is set to the cluster member inside
        # clustering execution.
        self._n_members = 1
        super().__init__(
            (self.x, self.y),
            data.radius_1 * 2,
            data.radius_2 * 2,
            angle=data.angle,
            alpha=0.65,
            linewidth=2,
            fill=False,
            **kwargs,
        )
        self.data = data

    @property
    def subframe(self):
        return io.get_subframe_by_tile_id(self.tile_id)

    def show_subframe(self, ax=None, aspect="auto"):
        if ax is None:
            _, ax = plt.subplots(figsize=calc_fig_size(8))
        ax.imshow(self.subframe, origin="upper", aspect=aspect)
        ax.set_axis_off()
        self.ax = ax

    def to_shapely(self):
        """Convert a markings.Blotch to shapely Ellipse.

        Code from https://gis.stackexchange.com/questions/243459/drawing-ellipse-with-shapely/243462
        """
        circ = geom.Point(self.center).buffer(1)
        ell = affinity.scale(circ, self.data.radius_1, self.data.radius_2)
        ellr = affinity.rotate(ell, self.data.angle)
        return ellr

    @property
    def area(self):
        return pi * self.data.radius_1 * self.data.radius_2

    @property
    def x1(self):
        return math.cos(math.radians(self.angle)) * self.data.radius_1

    @property
    def y1(self):
        return math.sin(self.angle) * self.data.radius_1

    @property
    def p1(self):
        return np.array(self.center) + np.array([self.x1, self.y1])

    @property
    def p2(self):
        return np.array(self.center) - np.array([self.x1, self.y1])

    @property
    def x2(self):
        return math.cos(math.radians(self.angle + 90)) * self.data.radius_2

    @property
    def y2(self):
        return math.sin(math.radians(self.angle + 90)) * self.data.radius_2

    @property
    def p3(self):
        return np.array(self.center) + np.array([self.x2, self.y2])

    @property
    def p4(self):
        return np.array(self.center) - np.array([self.x2, self.y2])

    @property
    def limit_points(self):
        return [self.p1, self.p2, self.p3, self.p4]

    def plot_center(self, ax, color="b"):
        return ax.scatter(self.x, self.y, color=color, s=20, marker=".")

    def plot_limit_points(self, ax, color="b"):
        for x, y in self.limit_points:
            ax.scatter(x, y, color=color, s=20, marker="o")

    def plot(self, color="red", ax=None, title=None):
        if ax is None:
            _, ax = plt.subplots()
        self.show_subframe(ax)
        ax = self.ax
        _remove_artist(self, "_last_patch")
        # Create a fresh Ellipse patch instead of adding the same artist
        patch = mpatches.Ellipse(
            (self.x, self.y),
            self.data.radius_1 * 2,
            self.data.radius_2 * 2,
            angle=self.data.angle,
            alpha=0.65,
            linewidth=2,
            fill=False,
        )
        if color is not None:
            patch.set_edgecolor(color)
        ax.add_patch(patch)
        if self.with_center:
            _remove_artist(self, "_last_center")
            self._last_center = ax.scatter(self.x, self.y, color=color, s=20, marker=".")
        if title is True:
            ax.set_title(self.tile_id)
        elif title:
            ax.set_title(title)
        set_subframe_size(ax)
        self._last_patch = patch

    def store(self, fpath=None):
        out = self.data
        for p in range(1, 5):
            attr = "p" + str(p)
            point = getattr(self, attr)
            out[attr + "_x"] = point[0]
            out[attr + "_y"] = point[1]
        if "image_id" not in out.index:
            pass
        if fpath is not None:
            out.to_hdf(str(fpath.with_suffix(".hdf")), "df")
        out["n_members"] = self.n_members
        return out

    def __str__(self):
        s = "markings.Blotch object. Input data:\n"
        s += self.data.__str__()
        s += "\n"
        s += "N_members: {}".format(self.n_members)
        return s

    def __repr__(self):
        mid = self.data.marking_id
        tile = self.data.tile_id
        area = float(self.area)
        meta = f"tile_id={tile!r}, area={area!r}"
        if mid is not None:
            return f"Blotch.from_marking_id({mid!r})  # {meta}"
        try:
            r1 = float(self.data.radius_1)
            r2 = float(self.data.radius_2)
        except Exception:
            r1 = getattr(self.data, "radius_1", None)
            r2 = getattr(self.data, "radius_2", None)
        return f"Blotch(marking_id={mid!r}, x={self.x:.2f}, y={self.y:.2f}, r1={r1}, r2={r2})  # {meta}"

# %% ../notebooks/01_markings.ipynb #b4qsyq61tus
class MarkingCollection:
    """Base class for Blotches and Fans containers."""
    _item_cls = None  # Override in subclass

    def __init__(self, df, color="green", **build_kwargs):
        self.df = df
        self.color = color
        self.collection = [
            self._item_cls(row, **build_kwargs)
            for _, row in self.df.iterrows()
        ]
        self._last_collection = None
        try:
            self.df["area"] = [item.area for item in self.collection]
            self.df["area_m2"] = self.df["map_scale"] ** 2 * self.df["area"]
        except Exception:
            pass

    @property
    def tile_id(self):
        try:
            return self.df.tile_id.iloc[0]
        except Exception:
            return getattr(self, "_tile_id", None)

    def _remove_last_collection(self):
        _remove_artist(self, "_last_collection")

    def __repr__(self):
        tid = getattr(self, "tile_id", None)
        n = len(self.collection)
        sample = [getattr(item.data, "marking_id", None) for item in self.collection[:3]]
        return f"{type(self).__name__}(tile_id={tid!r}, n={n}, sample={sample})"

# %% ../notebooks/01_markings.ipynb #65c9c604
class Blotches(MarkingCollection):
    """Container for Blotch objects with idempotent plotting."""
    _item_cls = Blotch

    def __init__(self, df, with_center=False, color="red"):
        super().__init__(df, color=color, with_center=with_center)

    @classmethod
    def from_tile_id(cls, tile_id, **kwargs):
        """Create a Blotches collection for all blotches of a tile."""
        df = io.get_blotches_for_tile(tile_id)
        return cls(df, **kwargs)

    def plot(self, ax=None, color=None, linewidth=2.0, **kwargs):
        """Plot all blotches as a PatchCollection on `ax`."""
        if ax is None:
            _, ax = plt.subplots()
        ax = show_subframe(self.tile_id, ax=ax)
        self._remove_last_collection()

        patches = []
        for b in self.collection:
            center = (float(b.data.x), float(b.data.y))
            width = float(b.data.radius_1) * 2
            height = float(b.data.radius_2) * 2
            angle = float(b.data.angle)
            p = mpatches.Ellipse(xy=center, width=width, height=height, angle=angle, alpha=0.65, linewidth=linewidth, fill=False)
            if color is not None:
                p.set_edgecolor(color)
            patches.append(p)

        pc = PatchCollection(patches, match_original=True)
        ax.add_collection(pc)
        set_subframe_size(ax)
        self._last_collection = pc
        return pc

# %% ../notebooks/01_markings.ipynb #02bedd36
def rotate_vector(v, angle):
    """Rotate vector by angle given in degrees.

    Parameters
    ----------
    v : np.array
        Vector to be rotated
    angle : float
        Angle in degrees
    """
    rangle = radians(angle)
    rotmat = np.array([[cos(rangle), -sin(rangle)], [sin(rangle), cos(rangle)]])
    # Ensure input is a 1-D numpy array of length 2
    v_arr = np.asarray(v, dtype=float).ravel()
    if v_arr.size != 2:
        raise ValueError(f"rotate_vector expects a length-2 vector, got shape {v_arr.shape}")
    return rotmat.dot(v_arr)

# %% ../notebooks/01_markings.ipynb #1fa605b1
class Fan(MarkingMixin, lines.Line2D):
    _catalog_getter = staticmethod(io.get_fan_catalog)
    to_average = "x y image_x image_y angle spread distance".split()

    def __init__(
        self,
        data,  # object with fan data attributes: x, y, angle, spread, distance
        scope="planet4",  # "planet4" or "hirise",
        with_center=False,  # accepted for API symmetry with Blotch; fans have no center, so ignored
        **kwargs,
    ):
        """
        Fan management class for P4.

        Attributes
        ----------
        to_average : list
            List of columns to average after clustering
        data : object with fan data attributes
            as provided by `data`.
        base : tuple
            base coordinates `x` and `y`.
        inside_half : float
            `data` divided by 2.0.
        armlength : float
            length of the fan arms.
        v1 : float[2]
            vector of first arm of fan.
        v2 : float[2]
        coords : float[3, 2]
            Set of coords to draw for MPL.Line2D object: arm1->base->arm2
        circle_base
        center
        radius
        midpoint
        base_to_midpoint_vec
        """
        self.data = data
        self.scope = scope if scope is not None else "planet4"
        if scope not in ["hirise", "planet4"]:
            raise TypeError("Unknown scope: {}".format(scope))
        # first coordinate is the base of fan
        actual_x = "x" if scope == "planet4" else "image_x"
        actual_y = "y" if scope == "planet4" else "image_y"
        try:
            self.base = np.asarray(self.data.loc[[actual_x, actual_y]].values.astype("float")).ravel()
        except KeyError:
            print("No x and y in the data:\n{}".format(data))
            raise KeyError
        # default n_members value (property)
        self._n_members = 1
        # angles
        self.inside_half = self.data.spread / 2.0
        alpha = self.data.angle - self.inside_half
        beta = self.data.angle + self.inside_half
        # length of arms
        # first arm
        self.v1 = np.asarray(rotate_vector([self.armlength, 0], alpha), dtype=float).ravel()
        # second arm
        self.v2 = np.asarray(rotate_vector([self.armlength, 0], beta), dtype=float).ravel()
        # vector matrix, stows the 1D vectors row-wise
        self.coords = np.vstack((self.base + self.v1, self.base, self.base + self.v2))
        # Validate coords shape
        if self.coords.shape != (3, 2):
            raise ValueError(f"Fan.coords expected shape (3,2), got {self.coords.shape}. base={self.base}, v1={self.v1}, v2={self.v2}")
        # init fan line, first column are the x-components of the row-vectors
        lines.Line2D.__init__(
            self,
            self.coords[:, 0],
            self.coords[:, 1],
            alpha=0.65,
            **kwargs,
        )

    @property
    def armlength(self):
        """Length of the fan arms.
        
        The trick is to realize: $d = h + r$, where _d_ is the measured distance,
        _h_ is the height of the triangle formed by the two arms, and _r_ is the radius
        of the semi-circle at the end of the fan. Using trigonometry, we can kick out r.
        """
        half = radians(self.inside_half)
        return self.data.distance / (cos(half) + sin(half))

    @property
    def area(self):
        tr_h = np.sqrt(self.armlength**2 - self.radius**2)
        tr_area = tr_h * self.radius
        half_circ_area = 0.5 * pi * self.radius**2
        return tr_area + half_circ_area

    @property
    def circle_base(self):
        "float[2] : Vector between end of first arm and second arm of fan."
        return self.v1 - self.v2

    @property
    def semi_circle_center(self):
        """float[2] : vector from base to mid-point between end of arms.

        This is used for the drawing of the semi-circle at the end of the
        two fan arms.
        """
        return self.base + self.v2 + 0.5 * self.circle_base

    @property
    def radius(self):
        "float : for the semi-circle wedge drawing at the end of fan."
        return 0.5 * LA.norm(self.circle_base)

    def add_semicircle(self, ax, color="b"):
        "Draw a semi-circle at end of fan arms using MPL.Wedge."
        # reverse order of arguments for arctan2 input requirements
        theta1 = degrees(arctan2(*self.circle_base[::-1]))
        theta2 = theta1 + 180
        wedge = mpatches.Wedge(
            self.semi_circle_center,
            self.radius,
            theta1,
            theta2,
            width=0.01 * self.radius,
            color=color,
            alpha=0.65,
        )
        _remove_artist(self, "_last_wedge")
        ax.add_patch(wedge)
        self._last_wedge = wedge

    def add_mean_wind_pointer(self, ax, color="b", ls="-"):
        "Draw a thicker mean wind direction pointer for better visibility in plots."
        endpoint = rotate_vector([3 * self.armlength, 0], self.data.angle)
        coords = np.vstack((self.base, self.base + endpoint))
        self.wind_pointer_end = coords[1]
        pointer = lines.Line2D(
            coords[:, 0], coords[:, 1], alpha=0.65, linewidth=1, linestyle=ls
        )
        pointer.set_color(color)
        ax.add_line(pointer)

    def plot(self, color='green', ax=None, title=None):
        if ax is None:
            _, ax = plt.subplots()
        ax = show_subframe(self.tile_id, ax=ax)
        _remove_artist(self, "_last_line")
        _remove_artist(self, "_last_wedge")
        # Create a fresh Line2D for plotting so the same Fan instance can be plotted multiple times
        line = lines.Line2D(self.coords[:, 0], self.coords[:, 1], alpha=0.65, color=color if color is not None else 'white')
        ax.add_line(line)
        self.add_semicircle(ax, color=color)
        if title is True:
            ax.set_title(self.tile_id)
        elif title:
            ax.set_title(title)
        set_subframe_size(ax)
        self._last_line = line
        return line

    @property
    def center(self):
        """Calculate vector to half total length.

        As total length, I define the armlength + the radius of the semi-circle
        at the end.
        """
        mid_point_vec = rotate_vector([0.5 * (self.armlength + self.radius), 0], self.data.angle)
        return self.base + mid_point_vec

    @property
    def base_to_center_vec(self):
        coords = np.vstack((self.base, self.center))
        return coords

    def add_midpoint_pointer(self, ax, color="b", ls="-"):
        coords = self.base_to_center_vec
        pointer = lines.Line2D(coords[:, 0], coords[:, 1], alpha=0.65, linewidth=3, linestyle=ls)
        pointer.set_color(color)
        ax.add_line(pointer)

    def __str__(self):
        out = "markings.Fan object. Input data:\n"

        out += "base: {0}\narmlength: {1}\narm1: {2}\narm2: {3}".format(self.base, self.armlength, self.base + self.v1, self.base + self.v2)
        return out

    def __repr__(self):
        mid = self.data.marking_id
        tile = self.data.tile_id
        area = float(self.area)
        meta = f"tile_id={tile!r}, area={area!r}"
        if mid is not None:
            return f"Fan.from_marking_id({mid!r})  # {meta}"
        try:
            bx, by = float(self.base[0]), float(self.base[1])
        except Exception:
            bx, by = (None, None)
        angle = getattr(self.data, 'angle', None)
        spread = getattr(self.data, 'spread', None)
        return f"Fan(marking_id={mid!r}, base=({bx:.2f},{by:.2f}), angle={angle}, spread={spread})  # {meta}"

    def store(self, fpath=None):
        out = self.data
        for i, arm in enumerate([self.v1, self.v2]):
            out["arm{}_x".format(i + 1)] = (self.base + arm)[0]
            out["arm{}_y".format(i + 1)] = (self.base + arm)[1]
        if "image_id" not in out.index:
            raise AttributeError("Storage of image_id failed.")
        if fpath is not None:
            out.to_hdf(str(fpath.with_suffix(".hdf")), "df")
        out["n_members"] = self.n_members
        return out

    def to_shapely(self):
        """Create a shapely half circle rotated by the fan's angle.

        Notes
        =====
        `Motivated by: <https://stackoverflow.com/a/30762727/680232>`_
        """
        centerx, centery = self.semi_circle_center

        start_angle = 270  # In degrees
        numsegments = 100

        theta = np.radians(np.linspace(start_angle, start_angle + 180, numsegments))
        x = centerx + self.radius * np.cos(theta)
        y = centery + self.radius * np.sin(theta)

        arc = geom.LineString(np.column_stack([x, y]))

        rotated = affinity.rotate(arc, self.data.angle, origin=tuple(self.semi_circle_center))

        rot_coords = np.array(list(rotated.coords))
        df = pd.DataFrame(np.vstack([self.coords[::-1][:2], rot_coords]))
        return geom.Polygon(df.round(2).drop_duplicates().values)

# %% ../notebooks/01_markings.ipynb #4d98f992
class Fans(MarkingCollection):
    """Container for Fan objects backed by a LineCollection for plotting."""
    _item_cls = Fan

    def __init__(self, df, scope="planet4", color="green", **kwargs):
        self.scope = scope
        super().__init__(df, color=color)
        self.segments = [np.asarray(f.coords, dtype=float) for f in self.collection]

    @classmethod
    def from_tile_id(cls, tile_id, **kwargs):
        """Create a Fans collection for all fans of a tile."""
        df = io.get_fans_for_tile(tile_id)
        return cls(df, **kwargs)

    def plot(self, ax=None, color=None, linewidth=1.0, **kwargs):
        """Plot all fans as a LineCollection on `ax`."""
        if ax is None:
            _, ax = plt.subplots()
        ax = show_subframe(self.tile_id, ax=ax)
        self._remove_last_collection()
        cols = color if color is not None else self.color
        lc = LineCollection(self.segments, colors=cols, linewidths=linewidth, **kwargs)
        ax.add_collection(lc)
        set_subframe_size(ax)
        self._last_collection = lc
        return lc

# %% ../notebooks/01_markings.ipynb #65997604
from functools import lru_cache

import geopandas as gpd
from pyproj import CRS, Transformer


@lru_cache(maxsize=8)
def _body_crs(body="mars", system="ocentric"):
    "IAU geographic CRS for `body` (via planetarypy.crs; lazy import)."
    from planetarypy.crs import body_crs
    return body_crs(body, system)


def _pixel_offsets_to_lonlat(dx, dy, lon0, lat0, north_azimuth, map_scale, geod):
    """Image-pixel outline offsets -> lon/lat.

    Empirically calibrated: east/north (m) =
    map_scale * [[-sin NA, cos NA], [cos NA, sin NA]] @ [dx, dy], then placed on
    the body with ``geod.fwd``. Reproduces ground_azimuth = (angle - north_azimuth)
    and length = px * map_scale.
    """
    na = np.deg2rad(north_azimuth)
    east = map_scale * (-np.sin(na) * dx + np.cos(na) * dy)
    north = map_scale * (np.cos(na) * dx + np.sin(na) * dy)
    dist = np.hypot(east, north)
    az = np.degrees(np.arctan2(east, north))
    lon, lat, _ = geod.fwd(np.full(dist.shape, lon0), np.full(dist.shape, lat0), az, dist)
    return lon, lat


def _to_target(lonlat, crs, body="mars", system="ocentric"):
    "Reproject an (N,2) lon/lat array into `crs` (pass through if crs is None)."
    if crs is None:
        return lonlat
    tr = Transformer.from_crs(_body_crs(body, system), CRS.from_user_input(crs),
                              always_xy=True)
    x, y = tr.transform(lonlat[:, 0], lonlat[:, 1])
    return np.column_stack([x, y])


def _fan_offsets(row, n_arc):
    "Approximate fan outline (apex + spread arc) as image-pixel offsets."
    ang = np.deg2rad(row.angle)
    half = np.deg2rad(row.spread) / 2.0
    L = row.distance
    phi = np.linspace(ang - half, ang + half, n_arc)
    return np.r_[0.0, L * np.cos(phi)], np.r_[0.0, L * np.sin(phi)]


def _blotch_offsets(row, n_ell):
    "Approximate blotch outline (ellipse) as image-pixel offsets."
    t = np.linspace(0, 2 * pi, n_ell, endpoint=False)
    ang = np.deg2rad(row.angle)
    ex = row.radius_1 * np.cos(t)
    ey = row.radius_2 * np.sin(t)
    return ex * np.cos(ang) - ey * np.sin(ang), ex * np.sin(ang) + ey * np.cos(ang)


def markings_to_geoseries(df, kind, crs=None, body="mars", system="ocentric",
                          n_arc=16, n_ell=48):
    """Approximate ground outlines for many markings as a GeoSeries.

    Fast, vectorized per marking (sector for fans, ellipse for blotches). Pass
    ``crs`` = a projected image's CRS to overlay on that raster, else lon/lat.
    For the exact outline of a single marking use ``Fan/Blotch.to_shapely_ground``.
    """
    if kind not in ("fan", "blotch"):
        raise ValueError("kind must be 'fan' or 'blotch'")
    geod = _body_crs(body, system).get_geod()
    offsets = _fan_offsets if kind == "fan" else _blotch_offsets
    n = n_arc if kind == "fan" else n_ell
    polys = []
    for _, row in df.iterrows():
        dx, dy = offsets(row, n)
        lon, lat = _pixel_offsets_to_lonlat(dx, dy, row.Longitude,
                                            row.PlanetocentricLatitude,
                                            row.north_azimuth, row.map_scale, geod)
        polys.append(geom.Polygon(_to_target(np.column_stack([lon, lat]), crs, body, system)))
    out_crs = CRS.from_user_input(crs) if crs is not None else _body_crs(body, system)
    return gpd.GeoSeries(polys, crs=out_crs)

