# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/07_panoptes_extract.ipynb.

# %% ../notebooks/07_panoptes_extract.ipynb #d4937c1c
from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# %% auto #0
__all__ = ['logger', 'TILE_X_STRIDE', 'TILE_Y_STRIDE', 'MAIN_WORKFLOW_ID', 'OUTPUT_COLUMNS', 'parse_subject_data',
           'parse_annotations', 'process_chunk', 'compute_image_coordinates', 'load_subjects_urls',
           'enrich_with_metadata', 'extract_panoptes_classifications']

# %% ../notebooks/07_panoptes_extract.ipynb #b2ec43cd
TILE_X_STRIDE = 740  # IMG_X_SIZE(840) - 100px overlap
TILE_Y_STRIDE = 548  # IMG_Y_SIZE(648) - 100px overlap

MAIN_WORKFLOW_ID = 12978

OUTPUT_COLUMNS = [
    "classification_id", "created_at", "image_id", "image_name",
    "image_url", "user_name", "marking", "x_tile", "y_tile",
    "acquisition_date", "local_mars_time",
    "x", "y", "image_x", "image_y",
    "radius_1", "radius_2", "distance", "angle", "spread", "version",
    "x_angle", "y_angle",
]

# %% ../notebooks/07_panoptes_extract.ipynb #13adf351
def parse_subject_data(subject_data_str: str) -> dict:
    """Parse the nested subject_data JSON and extract metadata fields.

    The subject_data JSON has structure: {"<subject_id>": {key: val, ...}}.
    Keys may have leading spaces or '!' prefixes that need stripping.

    Returns dict with keys: subject_id, tile_id, obsid, x_tile, y_tile, filename.
    """
    raw = json.loads(subject_data_str)
    subject_id = int(list(raw.keys())[0])
    inner = raw[str(subject_id)]

    # Normalize keys: strip whitespace and leading '!'
    cleaned = {k.strip().lstrip('!'): v for k, v in inner.items()}

    result = {'subject_id': subject_id}

    # tile_id: try old_planet_four_id first, then P4_subject_id
    result['tile_id'] = cleaned.get('old_planet_four_id') or cleaned.get('P4_subject_id')

    # obsid
    result['obsid'] = cleaned.get('hirise_image_id')

    # tile coordinates
    x_tile = cleaned.get('x_tile')
    y_tile = cleaned.get('y_tile')
    result['x_tile'] = int(x_tile) if x_tile is not None else None
    result['y_tile'] = int(y_tile) if y_tile is not None else None

    # filename (for old workflows or reference)
    result['filename'] = cleaned.get('filename')

    return result

# %% ../notebooks/07_panoptes_extract.ipynb #b8a2209e
def parse_annotations(annotations_str: str) -> list[dict]:
    """Parse the annotations JSON into a list of marking dicts.

    Workflow 12978 has two tasks: T1 (yes/no question) and T0 (drawing).
    We find the drawing task by looking for the first task whose value is a list.
    Returns one dict per marking. Empty value → [{"marking": "none"}].

    Fan (tool=0): x, y, distance (from radius), angle (from rotation), spread.
    Blotch (tool=1): x, y, radius_1 (from rx), radius_2 (from ry), angle.
    """
    ann = json.loads(annotations_str)

    # Find the drawing task — its value is a list (not a string like the yes/no task)
    values = []
    for task in ann:
        val = task.get('value', [])
        if isinstance(val, list):
            values = val
            break

    if not values:
        return [{"marking": "none"}]

    markings = []
    for v in values:
        if not isinstance(v, dict):
            continue
        tool = v.get('tool')
        if tool == 0:  # Fan
            markings.append({
                "marking": "fan",
                "x": v["x"],
                "y": v["y"],
                "distance": v.get("radius", np.nan),
                "angle": v.get("rotation", np.nan),
                "spread": v.get("spread", np.nan),
                "radius_1": np.nan,
                "radius_2": np.nan,
            })
        elif tool == 1:  # Blotch
            markings.append({
                "marking": "blotch",
                "x": v["x"],
                "y": v["y"],
                "radius_1": v.get("rx", np.nan),
                "radius_2": v.get("ry", np.nan),
                "angle": v.get("angle", np.nan),
                "spread": 0.0,
                "distance": np.nan,
            })

    if not markings:
        return [{"marking": "none"}]

    return markings

# %% ../notebooks/07_panoptes_extract.ipynb #a29173a4
def process_chunk(chunk: pd.DataFrame) -> pd.DataFrame:
    """Process one chunk of the classifications CSV into flat marking rows.

    Parses annotations and subject_data, then explodes so each marking
    becomes its own row.
    """
    # Parse annotations into lists of marking dicts
    chunk = chunk.copy()
    chunk["_markings"] = chunk.annotations.apply(parse_annotations)

    # Parse subject_data
    chunk["_subject"] = chunk.subject_data.apply(parse_subject_data)

    # Explode markings: one row per marking
    chunk = chunk.explode("_markings").reset_index(drop=True)

    # Extract marking geometry columns
    marking_df = pd.json_normalize(chunk["_markings"])
    subject_df = pd.json_normalize(chunk['_subject'])

    # Build output dataframe
    result = pd.DataFrame({
        "classification_id": chunk.classification_id.values,
        "created_at": chunk.created_at.values,
        "user_name": chunk.user_name.values,
        "version": chunk.workflow_version.values,
        "image_id": subject_df.tile_id.values,
        "image_name": subject_df.obsid.values,
        "x_tile": subject_df.x_tile.values,
        "y_tile": subject_df.y_tile.values,
        "subject_id": subject_df.subject_id.values,
        "marking": marking_df.marking.values,
        "x": marking_df.get("x", np.nan),
        "y": marking_df.get("y", np.nan),
        "radius_1": marking_df.get("radius_1", np.nan),
        "radius_2": marking_df.get("radius_2", np.nan),
        "distance": marking_df.get("distance", np.nan),
        "angle": marking_df.get("angle", np.nan),
        "spread": marking_df.get("spread", np.nan),
    })

    return result

# %% ../notebooks/07_panoptes_extract.ipynb #32f948d3
def compute_image_coordinates(df: pd.DataFrame) -> pd.DataFrame:
    """Add image_x and image_y from tile-scope x, y and tile indices.

    image_x = x + 740 * (x_tile - 1)
    image_y = y + 548 * (y_tile - 1)
    """
    df = df.copy()
    df['image_x'] = df.x + TILE_X_STRIDE * (df.x_tile - 1)
    df['image_y'] = df.y + TILE_Y_STRIDE * (df.y_tile - 1)
    return df

# %% ../notebooks/07_panoptes_extract.ipynb #a18758b8
def load_subjects_urls(subjects_csv: str | Path) -> pd.DataFrame:
    """Load subjects CSV and extract image URLs from the locations JSON.

    Returns DataFrame with columns: subject_id (int), image_url (str).
    """
    subjects = pd.read_csv(subjects_csv)

    def extract_url(locations_str):
        try:
            locs = json.loads(locations_str)
            return locs.get('0', '')
        except (json.JSONDecodeError, TypeError):
            return ''

    return pd.DataFrame({
        'subject_id': subjects.subject_id,
        'image_url': subjects.locations.apply(extract_url),
    })

# %% ../notebooks/07_panoptes_extract.ipynb #ebac0e3c
def enrich_with_metadata(
    df: pd.DataFrame,
    metadata: pd.DataFrame | None = None,
    tile_coords: pd.DataFrame | None = None,
) -> pd.DataFrame:
    """Join external metadata: fill missing tile coords, obsid, and acquisition_date.

    Some subjects in workflow 12978 have tile_id but no x_tile/y_tile/obsid.
    These are filled from tile_coords. acquisition_date comes from START_TIME.
    local_mars_time is set to NaN (requires SPICE computation).
    """
    df = df.copy()

    # Fill missing x_tile, y_tile, obsid from tile_coords
    if tile_coords is not None:
        missing_mask = df.x_tile.isna() & df.image_id.notna()
        if missing_mask.any():
            tc = tile_coords[['tile_id', 'x_tile', 'y_tile', 'obsid']].copy()
            tc = tc.rename(columns={'tile_id': 'image_id', 'obsid': '_obsid',
                                     'x_tile': '_x_tile', 'y_tile': '_y_tile'})
            df = df.merge(tc, on='image_id', how='left')

            # Fill missing values from tile_coords
            df['x_tile'] = df['x_tile'].fillna(df.get('_x_tile'))
            df['y_tile'] = df['y_tile'].fillna(df.get('_y_tile'))
            df['image_name'] = df['image_name'].fillna(df.get('_obsid'))

            df = df.drop(columns=['_x_tile', '_y_tile', '_obsid'], errors='ignore')

    # Join acquisition_date from metadata
    if metadata is not None:
        meta = metadata[['OBSERVATION_ID', 'START_TIME']].copy()
        meta['START_TIME'] = pd.to_datetime(meta.START_TIME)
        df = df.merge(
            meta.rename(columns={'OBSERVATION_ID': 'image_name', 'START_TIME': 'acquisition_date'}),
            on='image_name',
            how='left',
        )
    else:
        df['acquisition_date'] = pd.NaT

    df['local_mars_time'] = np.nan
    return df

# %% ../notebooks/07_panoptes_extract.ipynb #0b391477
def extract_panoptes_classifications(
    classifications_csv: str | Path,
    subjects_csv: str | Path | None = None,
    output_dir: str | Path | None = None,
    chunksize: int = 50_000,
) -> Path:
    """Extract Panoptes classifications CSV into a flat marking parquet file.

    Only processes the main workflow (12978). Old workflows (6321, 11388)
    are skipped with a warning.

    Parameters
    ----------
    classifications_csv : path to planet-four-classifications.csv
    subjects_csv : path to planet-four-subjects.csv (for image_url lookup)
    output_dir : directory for output file. Defaults to same dir as input.
    chunksize : rows per chunk for memory-bounded processing

    Returns
    -------
    Path to output parquet file
    """
    from p4tools import io

    classifications_csv = Path(classifications_csv)
    if output_dir is None:
        output_dir = classifications_csv.parent
    output_dir = Path(output_dir)

    # Load auxiliary data
    logger.info("Loading metadata and tile coords...")
    metadata = io.get_meta_data()
    tile_coords = io.get_tile_coords()

    subject_urls = None
    if subjects_csv is not None:
        logger.info("Loading subject URLs...")
        subject_urls = load_subjects_urls(subjects_csv)

    # Process in chunks
    accum = []
    skipped_workflows = {6321: 0, 11388: 0}
    n_processed = 0

    logger.info("Processing classifications...")
    reader = pd.read_csv(classifications_csv, chunksize=chunksize)

    for chunk in reader:
        # Count and skip old workflows
        for wf_id in skipped_workflows:
            skipped_workflows[wf_id] += (chunk.workflow_id == wf_id).sum()

        # Filter to main workflow
        main = chunk[chunk.workflow_id == MAIN_WORKFLOW_ID]
        if len(main) == 0:
            continue

        processed = process_chunk(main)
        accum.append(processed)
        n_processed += len(main)
        logger.info(f"Processed {n_processed} classifications...")

    # Log skipped workflows
    for wf_id, count in skipped_workflows.items():
        if count > 0:
            logger.warning(
                f"Skipped {count} classifications from workflow {wf_id} (not supported)"
            )

    # Concatenate all chunks
    logger.info("Concatenating results...")
    df = pd.concat(accum, ignore_index=True)
    logger.info(f"Total: {len(df)} marking rows from {n_processed} classifications")

    # Enrich with metadata (fills missing x_tile/y_tile/obsid and adds acquisition_date)
    df = enrich_with_metadata(df, metadata, tile_coords)

    # Compute image coordinates (after enrichment so x_tile/y_tile are filled)
    df = compute_image_coordinates(df)

    # Join image URLs
    if subject_urls is not None:
        df = df.merge(subject_urls, on='subject_id', how='left')
    else:
        df['image_url'] = ''

    # Deduplicate
    before = len(df)
    df = df.drop_duplicates(subset=["classification_id", "x", "y", "marking"])
    if len(df) < before:
        logger.warning(f"Removed {before - len(df)} duplicate rows")

    # Pre-clustering canonicalisation: drops NaN/out-of-frame markings,
    # canonicalises blotch geometry, computes x_angle/y_angle for DBSCAN.
    from p4tools.production.cleaning import clean_classifications
    df = clean_classifications(df, source="panoptes")

    # Select and reorder columns
    for col in OUTPUT_COLUMNS:
        if col not in df.columns:
            df[col] = np.nan
    df = df[OUTPUT_COLUMNS]

    # Write output
    outpath = output_dir / "panoptes_workflow_12978.parquet"
    df.to_parquet(outpath, index=False)
    logger.info(f"Written {len(df)} rows to {outpath}")

    return outpath
