"""Mars year definitions and temporal classification utilities."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/03_stats.ipynb.

# %% auto #0
__all__ = []

# %% ../notebooks/03_stats.ipynb #80103df1
import pandas as pd

from .io import mars_years, define_martian_year
