# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/03_stats.ipynb.

# %% auto 0
__all__ = ['mars_years', 'define_martian_year']

# %% ../notebooks/03_stats.ipynb 1
import pandas as pd


mars_years = {
    28: "2006-01-23",
    29: "2007-12-10",
    30: "2009-10-27",
    31: "2011-09-15",
    32: "2013-08-01",
    33: "2015-06-19",
    34: "2017-05-05",
    35: "2019-03-24",
    36: "2021-02-07",
    37: "2022-12-26",
    38: "2024-11-24",
    39: "2026-09-30",
    40: "2028-08-17",
}

# %% ../notebooks/03_stats.ipynb 2
def define_martian_year(df, time_col_name):
    """This Function Modifies the Dataframe it is given. And adds a Column named "MY",
        which signifies the Mars Year a Datapoint was taken.

    Parameters
    ----------
    df : pandas.DataFrame
        A Dataframe for which we wish to calculate the Mars Years
    time_col_name : str
        The Name of the column which has the Dates 
        which to correspond to Mars Years.
    """
    mars_timestamps = {k: pd.to_datetime(v) for k, v in mars_years.items()}
    df["MY"] = 0
    for yr, t in mars_timestamps.items():
        df.loc[df[time_col_name] > t, "MY"] = yr

